'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const M=require('../../matrix/core.js'),C=require('../../comparison/core.js'),V=require('../../vector-comparison/core.js'),VR=require('../../vector-comparison/render.js'),E=require('../core.js'),R=require('../render.js'),{createApp,loadObserved}=require('../../comparison/tests/dom-harness.cjs');
const root=path.resolve(__dirname,'../..'),data=loadObserved(),prepared=M.prepareDataset(data),raw=prepared.stations.find(s=>s.station.id==='146'),five=V.aggregate(raw,5);
const row=(minute,speed=1,to=90)=>({minute,timestamp:M.timestampAt(minute),status:speed===0?'calm':'valid',to:speed===0?null:to,record:{timestamp:M.timestampAt(minute),speedMps:speed,directionFromDeg:(to+180)%360}});
const missing=(minute,status='missing')=>({minute,timestamp:M.timestampAt(minute),status,to:null,record:null});
const sample=(slots,opts)=>E.sample({slots},opts),count=(s,p)=>(s.match(p)||[]).length,minutes=r=>Array.from(r.displayed,p=>p.slot.minute),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('input is raw, preserved exactly, and existing five-minute outputs remain unchanged',()=>{assert.throws(()=>E.sample(five),/one-minute RAW/);const before=JSON.stringify(raw),r=E.sample(raw);assert.equal(JSON.stringify(raw),before);assert.equal(r.slotCount,1440);assert.equal(r.inputCount,1439);assert.equal(r.calmCount,78);assert.equal(r.directionalCount,1361);assert.equal(JSON.stringify(five),JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,'orbit-event/tests/fixtures/before-five-minute-means.json')))));assert.equal(VR.polar(five),fs.readFileSync(path.join(root,'orbit-event/tests/fixtures/before-five-minute-b.svg'),'utf8'));for(const p of r.displayed)assert.equal(p.slot,raw.slots[p.slot.minute]);});
test('distance is from last displayed point, never the last input',()=>{const r=sample([0,.6,1.2,1.8,2.4].map((s,i)=>row(i,s)));assert.deepEqual(minutes(r),[0,2,4]);assert.deepEqual(r.displayed.map(p=>p.reason),['first-observation','distance','distance']);});
test('threshold is exactly the 0-to-1 m/s radius and includes equality',()=>{const r=sample([row(0,0),row(1,1),row(2,1.999999),row(3,2)]);assert.deepEqual(minutes(r),[0,1,3]);assert.equal(r.thresholdPx,49.5);assert.equal(r.thresholdMps,1);assert.equal(r.end.reason,'distance');assert.throws(()=>sample([],{thresholdPx:12}),/not a fixed pixel/);});
test('threshold tests vector Euclidean distance, not speed or angle difference alone',()=>{const a=row(0,1,0),b=row(1,1,60),c=row(2,1,90),r=sample([a,b,c]);assert.equal(r.displayed[1].slot.minute,1);close(r.displayed[1].distancePx,49.5);const tiny=sample([row(0,.1,0),row(1,.1,180),row(2,.1,0)]);assert.deepEqual(minutes(tiny),[0,2]);});
test('first and final raw observations always survive, including exact duplicate coordinates',()=>{const r=sample([row(4,.5),row(5,.6),row(6,.5)]);assert.deepEqual(minutes(r),[4,6]);assert.equal(r.end.reason,'final-endpoint');assert.equal(r.end.distancePx,0);assert.equal(r.edges.length,1);assert.notEqual(r.first.slot.timestamp,r.end.slot.timestamp);});
test('first and final calm records are real center points, with raw FROM and no TO',()=>{const slots=[{...row(1,0),record:{...row(1,0).record,directionFromDeg:237.4}},row(2,.2),{...row(3,0),record:{...row(3,0).record,directionFromDeg:119.9}}],r=sample(slots);assert.deepEqual(minutes(r),[1,3]);assert.equal(r.first.slot.record.directionFromDeg,237.4);assert.equal(r.end.slot.to,null);assert.deepEqual(E.project(r.first.slot),{x:295,y:262});assert.match(R.describe(r.first),/FROM 237.4°.*TO 정의 안 됨.*풍속 0 m\/s/);});
test('calm participates in normal distance sampling and does not create a gap',()=>{const r=sample([row(0,1.3),row(1,0),row(2,1.4)]);assert.deepEqual(minutes(r),[0,1,2]);assert.equal(r.runCount,1);assert.equal(r.edges.length,2);assert.equal(r.displayed[1].reason,'distance');assert.ok(r.edges.every(e=>e.from.run===e.to.run));});
test('missing and unavailable states restart the sampler without a bridge',()=>{for(const state of ['missing','unavailable']){const r=sample([row(0,.3),missing(1,state),row(2,.4),row(3,.5)]);assert.deepEqual(minutes(r),[0,2,3]);assert.equal(r.displayed[1].reason,'gap-restart');assert.equal(r.runCount,2);assert.equal(r.edges.length,1);assert.equal(r.edges[0].from.slot.minute,2);}const r=sample([row(0,.3),row(2,.4)]);assert.equal(r.edges.length,0);assert.equal(r.end.reason,'gap-restart');});
test('raw quality/code/duplicate problems become gaps; zero speed stays distinct from missing',()=>{const fixture=records=>M.prepareDataset({schemaVersion:'wind-matrix/1',kind:'test-fixture',dateLocal:M.DAY,timezone:M.ZONE,intervalMinutes:1,averagingPeriodMinutes:1,windDirectionEncoding:'kma-portal-mi1-avg-wd',stations:[{id:'T',acquisitionStatus:'complete'}],records}).stations[0];for(const bad of [{speedMps:null},{quality:'rejected'},{directionFromDeg:null},{directionFromDeg:360,rawValues:{MI1_AVG_WD:'360'}}]){const records=[0,1,2].map(m=>({stationId:'T',timestamp:M.timestampAt(m),speedMps:1.2,directionFromDeg:0}));Object.assign(records[1],bad);assert.equal(sample(fixture(records).slots).edges.length,0);}const records=[{stationId:'T',timestamp:M.timestampAt(0),speedMps:0,directionFromDeg:200},{stationId:'T',timestamp:M.timestampAt(1),speedMps:1.2,directionFromDeg:0}];assert.equal(sample(fixture(records).slots).edges.length,1);records.push({...records[1]});assert.equal(sample(fixture(records).slots).displayed.length,1);});
test('responsive uniform scales change CSS threshold but never selection',()=>{const expected=minutes(E.sample(raw));for(const w of [1,220,320,375.5,590,700,1180]){const r=E.sample(raw,{viewportWidth:w});assert.deepEqual(minutes(r),expected);close(r.thresholdPx,49.5*w/590);}const r=E.sample(raw,{viewportWidth:1180,viewportHeight:550});assert.equal(r.scale,1);assert.equal(r.thresholdPx,49.5);assert.deepEqual(minutes(r),expected);});
test('projection preserves circular TO and exact raw speed without angular bins',()=>{const a=row(0,1,359),b=row(1,1,1);assert.ok(Math.hypot(E.project(a).x-E.project(b).x,E.project(a).y-E.project(b).y)<2);assert.deepEqual(E.project(row(0,1,0)),{x:295,y:212.5});assert.deepEqual(E.project(row(0,1,90)),{x:344.5,y:262});assert.equal(E.project(missing(0)),null);});
test('actual chronology and independent U/V selection agree across all raw inputs',()=>{const expected=[];let last=null;for(const s of raw.slots){if(!['valid','calm'].includes(s.status)){last=null;continue;}const a=(s.record.directionFromDeg+180)*Math.PI/180,uv=s.status==='calm'?[0,0]:[s.record.speedMps*Math.sin(a),s.record.speedMps*Math.cos(a)];if(!last||Math.hypot(uv[0]-last.uv[0],uv[1]-last.uv[1])>=1-1e-12){expected.push(s.minute);last={uv,minute:s.minute};}}if(expected.at(-1)!==1439)expected.push(1439);const r=E.sample(raw);assert.deepEqual(minutes(r),expected);assert.equal(r.displayed.length,43);assert.equal(r.edges.length,42);assert.deepEqual(r.counts,{'first-observation':1,distance:41,'final-endpoint':1});for(const e of r.edges){assert.equal(e.from.run,e.to.run);for(let m=e.from.slot.minute;m<=e.to.slot.minute;m++)assert.ok(E.project(raw.slots[m]));}});
test('target-day endpoints are 00:01 and 23:59, never missing midnight or next-day midnight',()=>{const r=E.sample(raw);assert.equal(r.first.slot.minute,1);assert.equal(r.end.slot.minute,1439);assert.match(R.describe(r.first),/00:01 KST.*FROM 139.6°.*TO 319.6°.*풍속 0.8 m\/s/);assert.match(R.describe(r.end),/23:59 KST.*FROM 160.4°.*TO 340.4°.*풍속 0.5 m\/s/);assert.ok(!minutes(r).includes(0));assert.ok(!minutes(r).includes(1440));});
test('all 78 raw calm records retain numeric FROM, source metadata, and exact center',()=>{const calm=raw.slots.filter(s=>s.status==='calm');assert.equal(calm.length,78);for(const s of calm){assert.ok(Number.isFinite(s.record.directionFromDeg));assert.equal(s.to,null);assert.deepEqual(E.project(s),{x:295,y:262});assert.equal(s.record.speedMps,0);assert.ok(s.record.rawValues);assert.ok(s.record.sourceRow);}assert.equal(E.sample(raw).displayed.filter(p=>p.slot.status==='calm').length,1);});
test('TO inspector strips binary noise without altering the stored value',()=>{const slot=raw.slots[267],before=JSON.stringify(slot),p={slot,reason:'first-observation'};assert.equal(slot.record.directionFromDeg,184.4);assert.match(R.describe(p),/FROM 184.4°.*TO 4.4°/);assert.equal(JSON.stringify(slot),before);});
test('continuous point colors use actual minutes, not selected index or fixed time categories',()=>{assert.ok(new Set(raw.slots.map(s=>E.timeColor(s.minute))).size>1400);assert.notEqual(E.timeColor(600),E.timeColor(601));assert.equal(E.timeColor(0),'rgb(48,18,175)');assert.equal(E.timeColor(1439),'rgb(170,0,60)');for(const [f] of E.COLOR_STOPS.slice(1,-1)){const m=Math.round(f*1439),a=E.timeColor(m-1).slice(4,-1).split(',').map(Number),b=E.timeColor(m).slice(4,-1).split(',').map(Number);assert.ok(a.every((v,i)=>Math.abs(v-b[i])<=2));}});
test('renderer has only selected points, black edges, zero hourly glyphs and only endpoint emphasis',()=>{const r=E.sample(raw),s=R.polar(raw,r);assert.equal(count(s,/class="event-point"/g),43);assert.equal(count(s,/class="event-segment"/g),42);assert.equal(count(s,/class="event-start"/g),1);assert.equal(count(s,/class="event-end"/g),1);assert.equal(count(s,/mean-hour|hour-point|hour-label|mean-label|mean-hit|minute-hit-area/g),0);assert.ok(!s.includes('linearGradient'));for(const tag of s.match(/<line[^>]*class="event-segment"[^>]*>/g)){assert.match(tag,/stroke="#000000"/);assert.ok(!tag.includes('opacity'));}const selected=new Set(minutes(r));for(const [,m]of s.matchAll(/data-(?:bin|from-bin|to-bin)="(\d+)"/g))assert.ok(selected.has(+m));for(const p of r.displayed){assert.ok(s.includes(R.esc(R.describe(p))));assert.ok(s.includes(`fill="${E.timeColor(p.slot.minute)}"`));}});
test('empty and one-point datasets do not invent points, including actual unavailable AWS entries',()=>{for(const station of prepared.stations.filter(s=>!s.counts.valid)){const r=E.sample(station);assert.equal(r.displayed.length,0);assert.equal(r.edges.length,0);}assert.equal(sample([missing(0)]).first,null);const r=sample([row(8,0)]);assert.equal(r.first,r.end);assert.equal(r.edges.length,0);assert.equal(count(R.polar({slots:[]},r),/class="event-(?:start|end)"/g),2);for(const opts of [{viewportWidth:0},{viewportHeight:NaN},{viewportWidth:-1}])assert.throws(()=>E.sample(raw,opts),/positive finite/);});
function makeApp(input=data,options={}){const h=createApp('', 'VECTOR_COMPARE.html', {data:input,...options});return {app:h.window.WindOrbitEvent,n:h.nodes,resize:h.resize,host:h};}
test('DOM model loads the same view from raw only with exact initial observation',()=>{const {app,n}=makeApp();assert.equal(app.getResult().displayed.length,43);assert.equal(app.five,undefined);assert.match(n['event-summary'].textContent,/1분 원자료 1,439점 → 표시 43점/);assert.match(n['viewport-detail'].textContent,/49.50 CSS px/);assert.match(n['event-details'].textContent,/00:01 KST.*FROM 139.6°/);assert.equal(n['point-index'].textContent,'1 / 43');});
test('DOM hover, click pinning, mouseleave, keyboard and repeated buttons inspect selected raw points',()=>{const {app,n}=makeApp(),r=app.getResult(),target=r.displayed[30],p=n['event-plot'].querySelector(`[data-bin="${target.slot.minute}"]`);n['event-plot'].emit('mousemove',{target:p});assert.equal(n['event-details'].textContent,R.describe(target));assert.equal(app.getSelectedMinute(),1);n['event-plot'].emit('mouseleave');assert.match(n['event-details'].textContent,/00:01/);n['event-plot'].emit('click',{target:p});assert.equal(app.getSelectedMinute(),target.slot.minute);assert.match(n['event-details'].textContent,/TO 정의 안 됨.*풍속 0 m\/s/);n['event-next'].click();assert.equal(app.getSelectedMinute(),r.displayed[31].slot.minute);n['event-prev'].click();assert.equal(app.getSelectedMinute(),target.slot.minute);n['event-plot'].emit('keydown',{key:'End'});assert.equal(app.getSelectedMinute(),1439);n['event-next'].click();n['event-next'].click();assert.equal(app.getSelectedMinute(),1439);n['event-plot'].emit('keydown',{key:'Home'});n['event-prev'].click();assert.equal(app.getSelectedMinute(),1);n['event-plot'].emit('keydown',{key:'ArrowRight'});assert.equal(app.getSelectedMinute(),54);n['event-plot'].emit('keydown',{key:'ArrowLeft'});assert.equal(app.getSelectedMinute(),1);});
test('DOM responsive resampling preserves point identities and selected timestamp',()=>{const {app,n,resize}=makeApp();n['event-plot'].emit('keydown',{key:'End'});const before=minutes(app.getResult());n['event-plot'].box.width=320;resize();assert.deepEqual(minutes(app.getResult()),before);assert.equal(app.getSelectedMinute(),1439);assert.match(n['viewport-detail'].textContent,/26.85 CSS px/);assert.match(n['viewport-detail'].textContent,/320.0 CSS px/);assert.equal(n['point-index'].textContent,'43 / 43');n['event-plot'].box.width=0;resize();assert.equal(app.getResult().displayed.length,43);n['event-plot'].box.width=590;resize();assert.deepEqual(minutes(app.getResult()),before);});
test('DOM duplicate-position final point retains separate exact time through existing navigation',()=>{const input={schemaVersion:'wind-matrix/1',kind:'test-fixture',dateLocal:M.DAY,timezone:M.ZONE,intervalMinutes:1,averagingPeriodMinutes:1,windDirectionEncoding:'degrees-from-north',stations:[{id:'146',acquisitionStatus:'partial',acquiredRanges:[[1,3]]}],records:[1,2,3].map(m=>({stationId:'146',timestamp:M.timestampAt(m),speedMps:0,directionFromDeg:100+m}))}, {app,n}=makeApp(input);assert.deepEqual(minutes(app.getResult()),[1,3]);n['event-next'].click();assert.equal(app.getSelectedMinute(),3);assert.match(n['event-details'].textContent,/00:03.*FROM 103°/);n['event-prev'].click();assert.match(n['event-details'].textContent,/00:01.*FROM 101°/);});
test('event sampling is integrated in canonical Station View and the standalone page is removed',()=>{
 const html=fs.readFileSync(path.join(root,'VECTOR_COMPARE.html'),'utf8');assert.match(html,/1분 원자료/);assert.match(html,/orbit-event\/app.js/);assert.match(html,/vector-comparison\/app.js/);assert.equal(fs.existsSync(path.join(root,'ORBIT_EVENT.html')),false);
 for(const [,ref]of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert.ok(!/^https?:/.test(ref));assert.ok(fs.existsSync(path.join(root,ref.split('#')[0])),ref);}
});
test('event core, renderer and raw sources match the focused declared preservation manifest',()=>{
 const baseline=JSON.parse(fs.readFileSync(path.join(root,'verification/baseline.json')));
 const exclusions=JSON.parse(fs.readFileSync(path.join(root,'verification/public-release-exclusions.json')));
 assert.equal(exclusions.schema,'wind-public-release-exclusions/1');
 assert.equal(exclusions.excludedFiles.length,1);
 const excluded=exclusions.excludedFiles[0];
 assert.equal(excluded.path,'matrix/data/source/raw/jeonju-20241006-wind-only-public-preview.html');
 assert.equal(excluded.sha256,baseline.fileHashes[excluded.path]);
 assert.equal(excluded.runtimeRequired,false);
 assert.equal(fs.existsSync(path.join(root,excluded.path)),false,'Excluded portal capture must not be published');
 for(const [file,expected]of Object.entries(baseline.fileHashes)){if(file===excluded.path)continue;assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),expected,file);}
 const jj=baseline.stations.find(s=>s.id==='146'),r=E.sample(raw);
 assert.equal(crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex'),jj.event_sha256);
 assert.equal(crypto.createHash('sha256').update(R.polar(raw,r)).digest('hex'),jj.event_svg_sha256);
});
