/* Shared renderer for the offline page and data-derived static preview. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('../comparison/core.js'):root.WindComparisonCore,typeof module==='object'&&module.exports?require('./core.js'):root.WindOrbitEventCore);if(typeof module==='object'&&module.exports)module.exports=api;else root.WindOrbitEventRender=api;})(typeof globalThis!=='undefined'?globalThis:this,function(C,E){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])),n=v=>Number(v.toFixed(4));
const text=(x,y,s,a='')=>`<text x="${n(x)}" y="${n(y)}" ${a}>${esc(s)}</text>`,line=(x1,y1,x2,y2,a='')=>`<line x1="${n(x1)}" y1="${n(y1)}" x2="${n(x2)}" y2="${n(y2)}" ${a}/>`;
function reason(p){return p.reason==='final-endpoint'?'마지막 실제 관측점 보존':p.reason==='first-observation'?'첫 실제 관측점':p.reason==='gap-restart'?'자료 공백 뒤 첫 실제 관측점':`마지막 표시점에서 ${p.distancePx.toFixed(2)} CSS px 이동`;}
function describe(p){const s=p.slot,r=s.record,from=Number.isFinite(r.directionFromDeg)?`${r.directionFromDeg}°`:'미기록',to=s.status==='calm'?'정의 안 됨 (관측 무풍)':`${Number(s.to.toFixed(10))}°`;return `${C.clock(s.minute)} KST · 원자료 시각 ${r.timestamp||s.timestamp} · FROM ${from} · TO ${to} · 풍속 ${r.speedMps} m/s${s.status==='calm'?' · 영벡터 중심점':''} · ${reason(p)}`;}
function summary(result){return `1분 원자료 ${result.inputCount.toLocaleString('en-US')}점 → 표시 ${result.displayed.length}점 · 거리 조건 ${result.counts.distance||0} · 첫 점 ${result.counts['first-observation']||0} · 공백 뒤 재시작 ${result.counts['gap-restart']||0} · 끝점 예외 ${result.counts['final-endpoint']||0}`;}
function polar(entry,result){const {WIDTH:W,HEIGHT:H,CX:cx,CY:cy,RADIUS:R}=E,k=R/4;let s=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="#fafbf9"/>`;
 for(let r=1;r<=4;r++)s+=`<circle cx="${cx}" cy="${cy}" r="${r*k}" fill="none" stroke="#dce3dc"/>`+text(cx+5,cy-r*k+14,`${r} m/s`,'font-size="10" fill="#79897e"');
 for(let a=0;a<8;a++){const t=a*Math.PI/4;s+=line(cx,cy,cx+Math.sin(t)*R,cy-Math.cos(t)*R,'stroke="#e0e7e0"')+text(cx+Math.sin(t)*(R+22),cy-Math.cos(t)*(R+22)+4,['N','NE','E','SE','S','SW','W','NW'][a],'text-anchor="middle" font-size="12" fill="#56705e"');}
 // Only selected points participate in paths; time never colors a line.
 for(const {from:a,to:b} of result.edges)s+=line(a.x,a.y,b.x,b.y,`class="event-segment" data-from-bin="${a.slot.minute}" data-to-bin="${b.slot.minute}" data-run="${a.run}" stroke="#000000" stroke-width="1.25" vector-effect="non-scaling-stroke"`);
 for(const p of result.displayed)s+=`<g class="event-point" data-bin="${p.slot.minute}" data-reason="${p.reason}" data-run="${p.run}"><title>${esc(describe(p))}</title><circle cx="${n(p.x)}" cy="${n(p.y)}" r="3.2" fill="${E.timeColor(p.slot.minute)}" stroke="white" stroke-width=".85"/><circle cx="${n(p.x)}" cy="${n(p.y)}" r="6" fill="black" fill-opacity="0" pointer-events="all"/></g>`;
 // Exactly the global start/end receive special glyphs; labels remain legible when they overlap.
 if(result.first){const p=result.first;s+=`<g class="event-start" data-bin="${p.slot.minute}"><title>${esc('시작 · '+describe(p))}</title><circle cx="${n(p.x)}" cy="${n(p.y)}" r="8.5" fill="none" stroke="white" stroke-width="4"/><circle cx="${n(p.x)}" cy="${n(p.y)}" r="8.5" fill="none" stroke="${E.timeColor(p.slot.minute)}" stroke-width="2.4"/>`+line(p.x-8,p.y,p.x-23,p.y-21,'stroke="#000000" stroke-width=".8" pointer-events="none"')+text(p.x-26,p.y-23,`시작 ${C.clock(p.slot.minute)}`,'text-anchor="end" font-size="11" font-weight="700" fill="#273d2d" stroke="white" stroke-width="3" paint-order="stroke" pointer-events="none"')+'</g>';}
 if(result.end){const p=result.end,star=Array.from({length:10},(_,i)=>{const a=-Math.PI/2+i*Math.PI/5,r=i%2?3.9:9;return `${n(p.x+Math.cos(a)*r)},${n(p.y+Math.sin(a)*r)}`;}).join(' ');s+=`<g class="event-end" data-bin="${p.slot.minute}"><title>${esc('끝 · '+describe(p))}</title><polygon points="${star}" fill="${E.timeColor(p.slot.minute)}" stroke="white" stroke-width="1.5"/>`+line(p.x+8,p.y+2,p.x+23,p.y+23,'stroke="#000000" stroke-width=".8" pointer-events="none"')+text(p.x+26,p.y+29,`끝 ${C.clock(p.slot.minute)}`,'font-size="11" font-weight="700" fill="#273d2d" stroke="white" stroke-width="3" paint-order="stroke" pointer-events="none"')+'</g>';}
 s+=text(cx,H-32,'각도 TO · 반지름 원자료 풍속 0–4 m/s','text-anchor="middle" font-size="12" fill="#48634f"')+text(cx,H-12,'표시점만 시간순 연결 · 실제 공기 이동 경로 아님','text-anchor="middle" font-size="11" fill="#7a897b"');
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="상태 변화 기반 event sampling. 1분 원자료에서 마지막 표시점과의 화면 거리 ${result.thresholdPx.toFixed(2)} CSS px 기준, 현재 0에서 1 m/s의 반지름 길이. 시작과 끝만 별도 표시."><g font-family="Arial, Noto Sans CJK KR, sans-serif">${s}</g></svg>`;
}
return {esc,describe,reason,summary,polar};
});
