'use strict';
// Explicit DOM/history model only: no browser/layout/native input certification.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {ROOT,createApp}=require('../comparison/tests/dom-harness.cjs');
const plots=['path-chart','path-five','path-step','polar-chart','polar-five','polar-ten','event-plot'];
const page=()=>createApp('#station=146'),minutes=r=>Array.from(r.displayed,p=>p.slot.minute),selected=h=>h.cells().filter(c=>c.classList.contains('selected'));

test('canonical Station View loads seven plots, one Raw Matrix and all three current applications',()=>{
 const h=page();for(const id of plots)assert.ok(h.nodes[id].querySelector('svg'),id);assert.equal(h.cells().length,1440);assert.equal(h.nodes['wind-matrix'].tBodies[0].children.length,24);assert.equal(h.document.body.querySelectorAll('#wind-matrix').length,1);
 for(const f of ['comparison/app.js','vector-comparison/app.js','orbit-event/app.js'])assert.equal(h.scripts.filter(p=>p===f).length,1);
 assert.equal(h.window.WindVectorComparison.raw,h.app.getActiveStation());assert.equal(h.window.WindOrbitEvent.raw,h.app.getActiveStation());assert.match(h.nodes.summary.textContent,/5분 288구간/);assert.match(h.nodes.summary.textContent,/10분 144구간/);assert.doesNotMatch(h.nodes.summary.textContent,/undefined|NaN/);
});
test('canonical Jeonju retains 43 event points, 42 edges and distinct raw/mean/event marker rules',()=>{
 const h=page(),r=h.window.WindOrbitEvent.getResult(),p=h.nodes['event-plot'];assert.equal(r.inputCount,1439);assert.equal(r.displayed.length,43);assert.equal(r.edges.length,42);assert.deepEqual([r.first.slot.minute,r.end.slot.minute],[1,1439]);assert.equal(p.querySelectorAll('.event-point').length,43);assert.equal(p.querySelectorAll('.event-segment').length,42);assert.equal(p.querySelectorAll('.hour-point').length,0);assert.equal(p.querySelectorAll('.hour-label').length,0);assert.equal(h.nodes['polar-chart'].querySelectorAll('.hour-point').length,23);assert.equal(h.nodes['polar-five'].querySelectorAll('.mean-hour').length,24);
});
test('live pages have unique IDs, existing local resources, and only canonical Map/Station/National routes',()=>{
 for(const file of ['index.html','VECTOR_COMPARE.html','NATIONAL_COMPARE.html']){const html=fs.readFileSync(path.join(ROOT,file),'utf8'),ids=Array.from(html.matchAll(/\bid="([^"]+)"/g),m=>m[1]);assert.equal(ids.length,new Set(ids).size);
 for(const [,ref]of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert.ok(!/^https?:/.test(ref));const target=ref.split('#')[0];if(target)assert.ok(fs.existsSync(path.join(ROOT,target)),`${file}: missing ${target}`);if(/\.html$/.test(target))assert.ok(['index.html','VECTOR_COMPARE.html','NATIONAL_COMPARE.html'].includes(target));}}
 for(const file of ['ORBIT_EVENT.html','matrix.html','START_HERE.html'])assert.equal(fs.existsSync(path.join(ROOT,file)),false,file);
});
test('Map entry is Map-only, honors direct station hash and routes its links and buttons',()=>{
 const h=createApp('#station=243','index.html');assert.equal(h.app.getState().view,'map');assert.equal(h.app.getState().stationId,'243');assert.equal(h.nodes['station-view'],undefined);assert.equal(h.nodes['event-plot'],undefined);assert.equal(h.cells().length,0);assert.equal(h.nodes['national-tab'].getAttribute('href'),'NATIONAL_COMPARE.html');assert.equal(h.nodes['open-national'].getAttribute('href'),'NATIONAL_COMPARE.html');assert.match(h.nodes['national-entry-title'].textContent,/같은 시각, 지역별 바람 비교/);assert.equal(h.nodes['map-stations'].children.length,43);assert.equal(h.nodes['station-tab'].getAttribute('href'),'VECTOR_COMPARE.html#station=243');h.nodes['station-tab'].click();assert.equal(h.window.location.href,'VECTOR_COMPARE.html#station=243');h.nodes['open-jeonju'].click();assert.equal(h.window.location.href,'VECTOR_COMPARE.html#station=146');
});
test('Map and Station navigation carry the selected station',()=>{
 const h=page();h.app.selectStation('140');h.flush();assert.equal(h.nodes['map-tab'].getAttribute('href'),'index.html#station=140');h.nodes['map-tab'].click();assert.equal(h.window.location.href,'index.html#station=140');const m=createApp('#station=140','index.html'),markers=m.nodes['map-stations'].children.filter(n=>n.classList.contains('selected'));assert.equal(markers.length,1);assert.match(markers[0].getAttribute('aria-label'),/^군산 /);
});
test('dropdown updates raw, means, step, event and Matrix while preserving the chosen minute',()=>{
 const h=page();h.app.selectMinute(1380);h.nodes['station-select'].value='243';h.nodes['station-select'].emit('change');h.flush();const v=h.window.WindVectorComparison,e=h.window.WindOrbitEvent;assert.equal(h.app.getState().stationId,'243');assert.equal(h.app.getState().minute,1380);assert.equal(v.raw,h.app.getActiveStation());assert.equal(e.raw,v.raw);for(const d of [v.five,v.ten,v.steps])assert.equal(d.station.id,'243');assert.equal(h.nodes['detail-status'].textContent,'결측');assert.equal(h.cells()[1380].textContent,'×');assert.equal(h.nodes['missing-count'].textContent,'15');assert.match(h.nodes.summary.textContent,/부안/);assert.equal(selected(h)[0],h.cells()[1380]);for(const edge of e.getResult().edges)assert.ok(!(edge.from.slot.minute<1378&&edge.to.slot.minute>1392));
});
test('AWS selection contains no invented observations and returns cleanly to Jeonju',()=>{
 const h=page(),aws=h.window.WIND_MATRIX_DATA.stations.find(s=>s.network==='AWS');h.app.selectStation(aws.id);h.flush();assert.equal(h.nodes['empty-notice'].hidden,false);assert.equal(h.nodes['unacquired-count'].textContent,'1,440');assert.equal(h.cells().filter(c=>c.classList.contains('unavailable')).length,1440);assert.equal(h.window.WindOrbitEvent.getResult().displayed.length,0);assert.equal(h.nodes['point-index'].textContent,'0 / 0');assert.match(h.nodes['event-details'].textContent,/표시할 실제 관측점이 없습니다/);for(const s of h.window.WindVectorComparison.five.slots){assert.equal(s.n,0);assert.equal(s.record,null);}assert.equal(h.window.WindVectorComparison.steps.events.length,0);for(const id of ['path-chart','polar-chart'])assert.equal(h.nodes[id].querySelectorAll('.plot-point').length,0);for(const key of ['Home','End','ArrowLeft','ArrowRight'])assert.doesNotThrow(()=>h.nodes['event-plot'].emit('keydown',{key}));h.nodes['event-prev'].click();h.nodes['event-next'].click();h.app.selectStation('146');h.flush();assert.equal(h.nodes['empty-notice'].hidden,true);assert.equal(h.window.WindOrbitEvent.getResult().displayed.length,43);assert.equal(h.cells().filter(c=>c.classList.contains('valid')).length,1361);
});
test('station Back and Forward refresh derived views and exact raw tokens',()=>{
 const h=page();h.app.selectMinute(1380);h.app.selectStation('243');h.flush();h.app.selectStation('140');h.flush();h.window.history.back();h.flush();assert.equal(h.window.WindVectorComparison.raw.station.id,'243');assert.equal(h.window.WindOrbitEvent.raw.station.id,'243');assert.equal(h.nodes['detail-status'].textContent,'결측');h.window.history.forward();h.flush();assert.equal(h.window.WindVectorComparison.raw.station.id,'140');assert.equal(h.window.WindOrbitEvent.raw.station.id,'140');assert.equal(h.nodes['detail-status'].textContent,'방향 관측');assert.match(h.nodes['raw-values'].textContent,/군산/);
});
test('mean hover is temporary and click pins the shared raw Matrix and inspector',()=>{
 const h=page();h.app.selectMinute(10);const p=h.nodes['polar-five'].querySelector('[data-bin="720"]');h.nodes['polar-five'].emit('mousemove',{target:p});assert.equal(h.app.getState().minute,10);assert.match(h.nodes['detail-time'].textContent,/12:00/);assert.match(h.nodes.details.textContent,/12:00/);assert.equal(selected(h)[0],h.cells()[10]);h.nodes['polar-five'].emit('mouseleave');assert.match(h.nodes['detail-time'].textContent,/00:10/);h.nodes['polar-five'].emit('click',{target:p});assert.equal(h.app.getState().minute,720);assert.equal(selected(h)[0],h.cells()[720]);assert.match(h.nodes['raw-values'].textContent,/12:00/);
});
test('event hover is temporary; event pin and navigation synchronize exact raw observations',()=>{
 const h=page(),e=h.window.WindOrbitEvent,r=e.getResult(),point=r.displayed[20],target=h.nodes['event-plot'].querySelector(`[data-bin="${point.slot.minute}"]`);h.app.selectMinute(10);h.nodes['event-plot'].emit('mousemove',{target});assert.equal(e.getSelectedMinute(),1);assert.equal(h.app.getState().minute,10);h.nodes['event-plot'].emit('mouseleave');assert.match(h.nodes['event-details'].textContent,/00:01/);h.nodes['event-plot'].emit('click',{target});assert.equal(e.getSelectedMinute(),point.slot.minute);assert.equal(h.app.getState().minute,point.slot.minute);assert.equal(selected(h)[0],h.cells()[point.slot.minute]);h.nodes['event-next'].click();assert.equal(h.app.getState().minute,r.displayed[21].slot.minute);h.nodes['event-plot'].emit('keydown',{key:'End'});assert.equal(h.app.getState().minute,1439);assert.match(h.nodes['raw-values'].textContent,/23:59/);
});
test('resize and zero-width recovery retain event membership and selected timestamp',()=>{
 const h=page(),e=h.window.WindOrbitEvent;h.nodes['event-plot'].emit('keydown',{key:'End'});const before=minutes(e.getResult());for(const width of [220,320,375.5,590,700,1180]){h.nodes['event-plot'].box.width=width;h.resize();assert.deepEqual(minutes(e.getResult()),before);assert.equal(e.getSelectedMinute(),1439);assert.equal(h.app.getState().minute,1439);}h.nodes['event-plot'].box.width=0;h.resize();assert.deepEqual(minutes(e.getResult()),before);h.nodes['event-plot'].box.width=590;h.resize();assert.deepEqual(minutes(e.getResult()),before);
});
test('initial zero-width event plot is inert and recovers without a phantom observation',()=>{
 const h=createApp('#station=146','VECTOR_COMPARE.html',{eventWidth:0}),e=h.window.WindOrbitEvent;assert.equal(e.getResult(),null);for(const key of ['Home','End','ArrowLeft','ArrowRight'])assert.doesNotThrow(()=>h.nodes['event-plot'].emit('keydown',{key}));h.nodes['event-prev'].click();h.nodes['event-next'].click();assert.equal(h.app.getState().minute,1);h.nodes['event-plot'].box.width=590;h.resize();assert.equal(e.getResult().displayed.length,43);assert.equal(e.getSelectedMinute(),1);
});
test('raw selection clears stale mean hover and Matrix keyboard navigation stays bounded',()=>{
 const h=page();h.app.selectMinute(100);const p=h.nodes['path-five'].querySelector('[data-bin="720"]');h.nodes['path-five'].emit('mousemove',{target:p});assert.match(h.nodes.details.textContent,/12:00/);h.nodes['minute-input'].value='01:00';h.nodes['minute-input'].emit('change');assert.equal(h.app.getState().minute,60);assert.match(h.nodes.details.textContent,/01:00/);h.cells()[60].emit('keydown',{key:'Home',ctrlKey:true});assert.equal(h.app.getState().minute,0);h.nodes['previous-minute'].click();assert.equal(h.app.getState().minute,0);h.cells()[0].emit('keydown',{key:'End',ctrlKey:true});assert.equal(h.app.getState().minute,1439);h.nodes['next-minute'].click();assert.equal(h.app.getState().minute,1439);assert.equal(h.cells().filter(c=>c.tabIndex===0).length,1);
});
