'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),{createApp,loadObserved}=require('../../comparison/tests/dom-harness.cjs');
const M=require('../../matrix/core.js'),C=require('../../comparison/core.js'),R=require('../../comparison/render.js'),V=require('../core.js'),VR=require('../render.js'),root=path.resolve(__dirname,'../..');
const raw=M.prepareDataset(loadObserved()).stations.find(s=>s.station.id==='146'),five=V.aggregate(raw,5),ten=V.aggregate(raw,10),step=V.step(raw);
function count(s,p){return (s.match(p)||[]).length;}
test('all three Polar plots use exactly the same viewBox, radius, centers and scale',()=>{for(const s of [R.polar(raw),VR.polar(five),VR.polar(ten)]){assert.match(s,/viewBox="0 0 590 550"/);assert.match(s,/<circle cx="295" cy="262" r="198"/);for(const r of [49.5,99,148.5,198])assert.ok(s.includes(`r="${r}"`));}});
test('mean polar has mean-only segments, 24 bin-start hour marks and 8 3-hour labels',()=>{for(const [d,number]of [[five,240],[ten,105]]){const s=VR.polar(d);assert.equal(count(s,/class="mean-segment"/g),number);assert.equal(count(s,/class="mean-hour"/g),24);assert.equal(count(s,/class="mean-label"/g),8);assert.equal(count(s,/class="mean-hit"/g),d.slots.length);assert.ok(!s.includes('minute-hit-area'));assert.ok(!s.includes('plot-point'));assert.match(s,/data-bin="0" data-partial="true"/);assert.match(s,/구간 시작/);}});
test('raw actual-hour output stays unchanged and never fabricates midnight',()=>{const s=R.polar(raw);assert.equal(count(s,/class="hour-point"/g),23);assert.equal(count(s,/class="hour-label"/g),7);assert.ok(!/class="hour-point" data-minute="0"/.test(s));assert.equal(count(s,/class="plot-point minute-hit-area"/g),1439);});
test('invisible targets use exporter-safe explicit zero opacity',()=>{for(const s of [VR.polar(five),VR.polar(ten),VR.path(step,'step')]){assert.ok(!s.includes('fill="transparent"'));assert.match(s,/fill-opacity="0"/);}});
test('A comparison uses four faint timebands, common actual-minute x positions and monochrome paths',()=>{for(const d of [five,step]){const s=VR.path(d,d===step?'step':'mean');assert.match(s,/viewBox="0 0 1160 504"/);assert.ok(!s.includes('rgb('));for(const band of ['00–06','06–12','12–18','18–24'])assert.ok(s.includes(band));for(const status of ['무풍 ○','결측 ×','미확보 ·','상쇄 ×'])assert.ok(s.includes(status));assert.ok(s.includes('23:59'));}assert.match(VR.path(five),/data-bin="0"/);});
test('every lane-wrap pair takes short circular path and steps change vertically at the new minute',()=>{for(let a=0;a<16;a++)for(let b=0;b<16;b++){const parts=V.laneSegments({minute:10,status:'valid',to:a*22.5},{minute:15,status:'valid',to:b*22.5});assert.equal(parts.length,Math.abs(a-b)>8?2:1);if(parts.length===2){assert.equal(parts[0].x2,parts[1].x1);assert.ok(parts.every(s=>Math.abs(s.y2-s.y1)<=8));}const p=V.laneSegments({minute:15,status:'valid',to:a*22.5},{minute:15,status:'valid',to:b*22.5},true);assert.ok(p.every(s=>s.x1===15&&s.x2===15));}});
function makeApp(){const h=createApp();return {app:h.window.WindVectorComparison,n:h.nodes,host:h};}
test('DOM model: actual app loads all seven charts and honest initial raw/mean details',()=>{const {app,n}=makeApp();assert.equal(app.getMinute(),1);assert.equal(app.five.slots.length,288);for(const id of ['polar-chart','polar-five','polar-ten','path-chart','path-five','path-step','event-plot'])assert.match(n[id].innerHTML,/<svg/);assert.match(n.details.textContent,/4\/5분/);assert.match(n.details.textContent,/9\/10분/);assert.match(n['raw-values'].textContent,/00:01/);});
test('DOM model: minute selection covers missing midnight, bounds, time input, keyboard and invalid input',()=>{const {app,n}=makeApp();app.selectMinute(0);assert.match(n.details.textContent,/미확보/);assert.match(n['raw-values'].textContent,/원본 행 없음/);n['previous-minute'].click();assert.equal(app.getMinute(),0);n['next-minute'].click();assert.equal(app.getMinute(),1);n['minute-input'].value='23:59';n['minute-input'].emit('change',{target:n['minute-input']});assert.equal(app.getMinute(),1439);n['next-minute'].click();assert.equal(app.getMinute(),1439);n['path-step'].emit('keydown',{key:'Home'});assert.equal(app.getMinute(),0);n['polar-five'].emit('keydown',{key:'ArrowRight'});assert.equal(app.getMinute(),1);n['minute-input'].value='25:00';n['minute-input'].emit('change',{target:n['minute-input']});assert.equal(n['minute-input'].value,'00:01');});
test('DOM model: mean hover is temporary, click persists and raw token details remain available',()=>{const {app,n}=makeApp(),p=n['polar-five'].querySelector('[data-bin="720"]');assert.ok(p);n['polar-five'].emit('mousemove',{target:p});assert.match(n.details.textContent,/12:00/);assert.equal(app.getMinute(),1);n['polar-five'].emit('mouseleave');assert.match(n['raw-values'].textContent,/00:01/);n['polar-five'].emit('click',{target:p});assert.equal(app.getMinute(),720);n['polar-five'].emit('mouseleave');assert.match(n['raw-values'].textContent,/12:00/);});
test('canonical offline page only loads existing local resources and Map View links to it',()=>{const html=fs.readFileSync(path.join(root,'VECTOR_COMPARE.html'),'utf8');for(const [,file]of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert.ok(!/^https?:/.test(file));const p=file.split('#')[0];if(p)assert.ok(fs.existsSync(path.join(root,p)),p);}assert.match(fs.readFileSync(path.join(root,'index.html'),'utf8'),/href="VECTOR_COMPARE.html"/);});
