"use strict";
const test=require('node:test'),assert=require('node:assert/strict');
const {load,plain}=require('./national-harness.cjs');
const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);

test('original v0.10 renderer supplies full quantitative bars and no C renderer is loaded',()=>{
 const a=load(),p=a.inspect('108'),r=a.renderState();assert.equal(r.motionModel,'D-passage');assert.equal(r.cycleSeconds,4);assert.equal(p.mode,'full');near(p.length,p.speed*a.state().visualUnit);near(p.visibleLength,p.length);near(p.start,-p.length/2);near(p.end,p.length/2);assert.ok(a.scripts.includes('national/legacy-renderer.js'));assert.ok(a.scripts.includes('national/v010-adapter.js'));assert.ok(!a.scripts.includes('national/particle-renderer.js'));assert.equal(a.nodes['flow-canvas'].hidden,true);assert.equal(a.canvases['flow-canvas'].frame.length,0);assert.ok(a.canvases['particle-canvas'].frame.some(c=>c.type==='stroke'&&c.lineCap==='butt'&&c.color==='#111111'));assert.ok(a.canvases['direction-canvas'].frame.some(c=>c.color==='#b72b2e'));
});
test('moving v0.10 bars use the unchanged passage geometry, station phase and TO rotation',()=>{
 const a=load();a.click('seoul-preset');a.click('motion-toggle');for(const t of [0,120,500,1000,1600,2500,4000]){a.tick(t);const p=a.inspect('108'),r=a.renderState(),M=a.window.PassageModel,G=a.window.ObservationsCore,expected=M.geometry(p.speed,M.phaseForStation('108')+r.seconds/M.duration,0,1,r.scale,r.unit,false,true);for(const k of ['phase','length','start','end','visibleLength','trackLength'])near(p[k],expected[k]);const rotated=G.rotateLocal(expected.start,expected.end,expected.y,p.from);for(const k of ['x1','x2','y1','y2'])near(p[k],rotated[k]);assert.equal(p.current,true);assert.equal(p.birth,null);assert.equal(a.canvases['flow-canvas'].frame.length,0);}a.click('motion-toggle');assert.equal(a.inspect('108').mode,'full');
});
test('geographic coverage stays aligned for original bars, station markers and selected exceptions',()=>{
 const a=load();let ids=a.state().displayPolicy.ids;assert.deepEqual(plain(a.renderState().flow.displayedStationIds).sort(),plain(ids).sort());const hidden=a.history.stations.find(s=>!ids.includes(s.id));assert.equal(a.inspect(hidden.id),null);a.input('station-search',hidden.id);a.nodes['station-list'].children.find(n=>n.getAttribute('aria-label')?.includes(`지점 ${hidden.id},`)).click();assert.ok(a.inspect(hidden.id));assert.ok(a.state().displayPolicy.ids.includes(hidden.id));a.click('seoul-preset');assert.equal(a.renderState().flow.displayedStationIds.length,638);a.click('zoom-reset');assert.ok(a.renderState().flow.displayedStationIds.length<638);
});
test('quantitative legend and the existing geographic north/scale survive zoom, resize and symbol size',()=>{
 const a=load(),value=a.inspect('108').speed;assert.ok(a.nodes['national-scale-label'].textContent.includes('km'));assert.ok(a.html.includes('북쪽이 위'));const geoScale=a.nodes['national-scale-line'].getAttribute('d');a.input('scale',1.5);near(a.inspect('108').length,value*a.state().visualUnit*1.5);assert.equal(a.nodes['national-scale-line'].getAttribute('d'),geoScale);a.click('seoul-preset');const speed=Number(a.nodes['legend-measure'].getAttribute('data-reference-speed')),r=a.renderState();near(parseFloat(a.nodes['legend-measure'].style.width),speed*r.unit*r.scale*6);a.resize(500,760);assert.ok(a.nodes['national-scale-label'].textContent.includes('km'));assert.equal(a.inspect('108').speed,value);assert.equal(a.nodes['wind-value'].textContent,String(value));assert.ok(a.nodes['cell-status'].textContent.length>0);
});
