'use strict';
// Actual HTML/script controller exercised in a DOM and Canvas command model.
// No actual browser, rendered-pixel, or visual acceptance claim is made here.
const test=require('node:test'),assert=require('node:assert/strict');
const {load,history,plain}=require('./national-harness.cjs');
const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const sample=(i,p,id)=>history.frames[i].samples[String(p)].find(s=>s.id===String(id));
const toText=from=>`${Number(((from+180)%360).toFixed(8))}°`;
function select(a,id){a.input('station-search',id);const b=a.nodes['station-list'].children.find(n=>n.getAttribute('aria-label')?.includes(`지점 ${id},`));assert.ok(b,`search returned station ${id}`);b.click();}

test('actual National HTML initializes only the original v0.10 expression, 638 stations and 61 history frames',()=>{
 const a=load(),s=a.state();assert.equal(s.representation,'baseline');assert.equal(a.doc.body.dataset.representation,'baseline');assert.equal(s.stations,638);assert.equal(s.timeCount,61);assert.equal(s.timeIndex,60);assert.equal(s.datasetId,'kma-history-20261003');assert.equal(s.selected,'108');assert.equal(s.period,1);assert.equal(s.motion,false);assert.equal(s.playing,false);assert.equal(a.nodes.stations.children.length,638);assert.equal(a.nodes['station-count'].textContent,'638');assert.equal(a.nodes.timeline.max,'60');assert.equal(a.nodes['time-position'].textContent,'61 / 61개 시각');assert.deepEqual(plain(a.datasetState().periods),[1,10]);assert.equal(a.datasetState().times.length,61);assert.equal(a.doc.getElementById('invented-missing-control'),null);assert.equal(a.renderState().flow.retainedHistory,false);
 for(const id of ['candidate-lanes','candidate-comet','candidate-ribbon','candidate-baseline','file-input','dataset-select','temperature-toggle','density','replay-style','reset-button'])assert.equal(a.doc.getElementById(id),null,`${id} must not be manufactured or exposed`);
 assert.ok(a.scripts.every(s=>s.startsWith('national/')));assert.ok(!a.scripts.some(s=>/temperature|observations-data/.test(s)));
});

test('every raw speed and FROM survives all 638 stations × 61 frames × both source means',()=>{
 const a=load();let comparisons=0;for(const p of [1,10]){a.change('period',p);for(let i=0;i<61;i++){a.input('timeline',i);const s=a.state();assert.equal(s.weatherTime,Date.parse(history.frames[i].time));assert.equal(s.period,p);assert.equal(s.interpolated,false);assert.equal(s.stations,638);assert.equal(s.timeIndex,i);assert.equal(Object.keys(s.values).length,638);for(const row of history.frames[i].samples[String(p)]){assert.equal(s.values[row.id].speed,row.speed,`speed ${p}/${i}/${row.id}`);assert.equal(s.values[row.id].from,row.from,`FROM ${p}/${i}/${row.id}`);comparisons++;}}}assert.equal(comparisons,77836);assert.equal(a.renderState().flow.spatialInterpolation,false);assert.equal(a.renderState().flow.temporalInterpolation,false);
});

test('dates and stored endpoints are actual National KST observations, distinct from Station data',()=>{
 const a=load();assert.equal(a.nodes['date-label'].textContent,'2026.10.03 · KST');assert.equal(a.nodes['clock-time'].textContent,'15:32:00');assert.equal(a.nodes['map-time'].textContent,'15:32 KST');assert.match(a.nodes['source-credit'].textContent,/2026-10-03 15:32 KST/);assert.match(a.html,/2026-10-03 14:32–15:32 KST/);assert.match(a.html,/2024-10-06/);assert.match(a.html,/별도|서로 다른 자료/);a.input('timeline',0);assert.equal(a.nodes['clock-time'].textContent,'14:32:00');assert.equal(a.state().weatherTime,Date.parse('2026-10-03T14:32:00+09:00'));assert.match(a.nodes['time-gap'].textContent,/저장된 시각만 표시 · 보간 없음/);
});

test('hover and selected panel expose unrounded current raw speed, FROM and converted TO',()=>{
 const a=load();for(const [i,p,id]of [[0,1,'116'],[11,1,'146'],[12,1,'146'],[60,1,'108'],[47,10,'400']]){a.change('period',p);a.input('timeline',i);const row=sample(i,p,id);assert.ok(row.speed>0&&row.from!==null);select(a,id);a.marker(id).emit('mouseenter');assert.equal(a.nodes['wind-value'].textContent,String(row.speed));assert.equal(a.nodes['from-value'].textContent,`${row.from}°`);assert.equal(a.nodes['to-value'].textContent,toText(row.from));assert.equal(a.nodes['average-value'].textContent,`${p}분 평균`);assert.ok(a.nodes['station-hover'].textContent.includes(`${row.speed} m/s`));assert.ok(a.nodes['station-hover'].textContent.includes(`FROM ${row.from}°`));assert.ok(a.nodes['station-hover'].textContent.includes(`TO ${toText(row.from)}`));assert.equal(a.nodes['selected-direction'].hidden,false);assert.ok(a.nodes['selected-direction-text'].textContent.includes(`TO ${toText(row.from)}`));assert.equal(a.nodes['qc-value'].textContent,'정보 미제공');assert.equal(a.state().selected,id);}
 // Hover remains on the same station and refreshes after a seek.
 a.change('period',1);a.input('timeline',0);const row=sample(0,1,'400');assert.ok(a.nodes['station-hover'].textContent.includes(`FROM ${row.from}°`));a.marker('400').emit('mouseleave');assert.match(a.nodes['station-hover'].textContent,/지점을 선택하면/);
});

test('search includes hidden overview stations and both complete ASOS/AWS networks',()=>{
 const a=load(),hidden=history.stations.find(s=>!a.state().displayPolicy.ids.includes(s.id));assert.ok(hidden);assert.equal(a.marker(hidden.id).style.display,'none');select(a,hidden.id);assert.equal(a.state().selected,hidden.id);assert.equal(a.marker(hidden.id).style.display,'');assert.ok(a.state().displayPolicy.ids.includes(hidden.id));assert.equal(a.state().stations,638);
 a.input('station-search','ASOS');assert.match(a.nodes['search-count'].textContent,/검색 98개 · 전체 638개/);a.input('station-search','AWS');assert.match(a.nodes['search-count'].textContent,/검색 540개 · 전체 638개/);a.input('station-search','');assert.equal(a.nodes['station-list'].children.length,40);for(let i=0;i<15;i++)a.click('more-stations');assert.equal(a.nodes['station-list'].children.length,638);assert.equal(a.nodes['more-stations'].hidden,true);a.input('station-search','서울');assert.ok(a.nodes['station-list'].textContent.includes('서울 108'));a.input('station-search','no-such-station');assert.match(a.nodes['search-count'].textContent,/검색 0개/);assert.match(a.nodes['station-list'].textContent,/일치하는 지점이 없습니다/);
});

test('overview geographic membership is stable across means, times, labels, scale and viewport resize',()=>{
 const a=load(),ids=plain(a.state().displayPolicy.ids),values=plain(a.state().values);assert.ok(ids.length>0&&ids.length<638);assert.equal(a.state().displayPolicy.threshold,4);assert.equal(a.state().displayPolicy.rule,'fixed-geographic-cell-nearest-center-then-spacing');a.change('period',10);a.input('timeline',30);assert.deepEqual(plain(a.state().displayPolicy.ids),ids);a.change('label-mode','all');a.input('scale',1.5);a.resize(480,700);assert.deepEqual(plain(a.state().displayPolicy.ids),ids);a.change('label-mode','off');assert.equal(a.layoutState().labels.length,0);a.change('period',1);a.input('timeline',60);assert.deepEqual(plain(a.state().values),values);assert.equal(a.state().scale,1.5);
});

test('zoom reveals all 638 at 4× and resets to overview; pan is bounded and preserves raw values',()=>{
 const a=load(),values=plain(a.state().values);for(const z of [1.5,2,3]){a.click('zoom-in');assert.equal(a.state().zoom,z);assert.equal(a.state().displayPolicy.all,false);}a.click('zoom-in');assert.equal(a.state().zoom,4);assert.equal(a.state().displayPolicy.all,true);assert.equal(a.state().displayPolicy.ids.length,638);assert.equal(a.nodes.stations.children.filter(n=>n.style.display!=='none').length,638);assert.equal(a.renderState().flow.displayedStationIds.length,638);
 const prior=plain(a.layoutState().view),map=a.nodes.map;map.emit('pointerdown',{pointerId:4,button:0,clientX:200,clientY:200});map.emit('pointermove',{pointerId:4,clientX:240,clientY:225});map.emit('pointerup',{pointerId:4});assert.notDeepEqual(plain(a.layoutState().view),prior);assert.equal(map.capturedPointer,null);assert.equal(a.nodes.map.getAttribute('viewBox'),a.nodes['observation-map'].getAttribute('viewBox'));assert.equal(map.emit('click').defaultPrevented,true);const v=a.layoutState().view;assert.ok(v.x>=0&&v.y>=0&&v.x+v.w<=1000&&v.y+v.h<=760);assert.deepEqual(plain(a.state().values),values);a.click('zoom-reset');assert.equal(a.state().zoom,1);assert.equal(a.state().displayPolicy.all,false);assert.deepEqual(plain(a.layoutState().view),{x:0,y:0,w:1000,h:760});a.click('seoul-preset');assert.equal(a.state().selected,'108');assert.equal(a.state().zoom,6);assert.equal(a.state().displayPolicy.ids.length,638);
});

test('seek, previous and next pause both clocks and clamp at exact stored endpoints',()=>{
 const a=load();a.input('timeline',0);assert.equal(a.state().timeIndex,0);assert.equal(a.nodes['time-prev'].disabled,true);a.click('time-prev');assert.equal(a.state().timeIndex,0);a.click('time-next');assert.equal(a.state().timeIndex,1);a.click('time-play');assert.equal(a.state().playing,true);assert.equal(a.state().motion,true);a.tick(400);a.input('timeline',30);assert.equal(a.state().timeIndex,30);assert.equal(a.state().playing,false);assert.equal(a.state().motion,false);const d=a.renderState().seconds;a.tick(1400);assert.equal(a.renderState().seconds,d);a.click('time-prev');assert.equal(a.state().timeIndex,29);a.click('time-next');assert.equal(a.state().timeIndex,30);a.input('timeline',999);assert.equal(a.state().timeIndex,60);assert.equal(a.nodes['time-next'].disabled,true);a.click('time-next');assert.equal(a.state().timeIndex,60);a.input('timeline',-100);assert.equal(a.state().timeIndex,0);
});

test('primary play, pause, rate change, replay restart and final frame stop both clocks',()=>{
 const a=load();a.click('time-play');assert.equal(a.state().timeIndex,0);assert.equal(a.state().playing,true);assert.equal(a.nodes['motion-toggle'].disabled,true);a.tick(1000);assert.equal(a.state().timeIndex,1);a.click('time-play');assert.equal(a.state().playing,false);assert.equal(a.state().motion,false);const d=a.renderState().seconds;a.tick(2000);assert.equal(a.renderState().seconds,d);a.change('play-rate',2);a.click('time-play');a.tick(2500);assert.equal(a.state().timeIndex,2);a.change('period',10);assert.equal(a.state().playing,true);assert.equal(a.state().motion,true);assert.equal(a.state().period,10);a.tick(3000);assert.equal(a.state().timeIndex,3);a.input('timeline',59);a.click('time-play');a.tick(3500);assert.equal(a.state().timeIndex,60);assert.equal(a.state().playing,false);assert.equal(a.state().motion,false);assert.equal(a.nodes['motion-toggle'].disabled,false);assert.match(a.nodes['time-play'].textContent,/처음부터/);const end=a.renderState().seconds;a.tick(7000);assert.equal(a.renderState().seconds,end);a.click('time-play');assert.equal(a.state().timeIndex,0);assert.equal(a.state().playing,true);
});

test('fixed-time current motion changes only phase; discrete observed turns do not interpolate or keep paths',()=>{
 const a=load();a.input('timeline',11);const values=plain(a.state().values),time=a.state().weatherTime;a.click('motion-toggle');a.tick(0);a.tick(500);select(a,'146');const before=a.inspect('146');assert.equal(before.from,150.9);assert.equal(a.state().weatherTime,time);assert.deepEqual(plain(a.state().values),values);assert.equal(a.state().playing,false);a.input('timeline',12);const after=a.inspect('146');assert.equal(after.from,333.6);assert.equal(after.phase,before.phase);assert.notDeepEqual(after.from,before.from);assert.equal(after.current,true);assert.equal(after.birth,null);assert.equal(a.renderState().flow.retainedHistory,false);a.tick(1500);assert.equal(a.inspect('146').phase,after.phase);a.click('motion-toggle');a.tick(2500);assert.ok(a.inspect('146').phase!==after.phase);a.click('motion-toggle');const d=a.renderState().seconds;a.tick(3500);assert.equal(a.renderState().seconds,d);assert.equal(a.state().timeIndex,12);
});

test('hidden-document time is excluded and restored without skipping stored observations',()=>{
 const a=load();a.input('timeline',0);a.click('time-play');a.tick(0);a.tick(200);const d=a.renderState().seconds;a.doc.hidden=true;a.doc.emit('visibilitychange');a.tick(5000);assert.equal(a.renderState().seconds,d);assert.equal(a.state().timeIndex,0);a.doc.hidden=false;a.doc.emit('visibilitychange');a.tick(6000);assert.equal(a.state().timeIndex,0);a.tick(7000);assert.equal(a.state().timeIndex,1);
});

test('real missing-speed, missing-direction and calm observations draw no fabricated direction or moving glyph',()=>{
 const a=load();for(const [i,id,status]of [[0,'504','missing'],[56,'252','direction-missing'],[0,'129','calm']]){a.input('timeline',i);select(a,id);const r=sample(i,1,id),p=a.inspect(id);assert.equal(p.status,status);assert.equal(p.speed,r.speed);assert.equal(p.from,r.from);assert.equal(p.head.visible,false);assert.equal(a.nodes['selected-direction'].hidden,true);const mark=a.marker(id).querySelector(status==='calm'?'.calm-mark':'.missing-mark');assert.equal(mark.style.display,'');assert.equal(a.nodes['wind-value'].textContent,r.speed===null?'—':String(r.speed));assert.equal(a.nodes['to-value'].textContent,status==='calm'?'무풍':'결측');assert.equal(a.canvases['flow-canvas'].frame.filter(c=>Math.abs(c.transform[4]-p.anchor.x)<1e-8&&Math.abs(c.transform[5]-p.anchor.y)<1e-8).length,0);}
});

test('actual 0.1 m/s observations retain exact fractional length and the original four-second phase',()=>{
 const a=load();a.input('timeline',30);for(const id of ['116','425','545','587','768','831']){select(a,id);const p=a.inspect(id);assert.equal(p.speed,.1);near(p.length,.1*a.state().visualUnit);near(p.visibleLength,p.length);assert.equal(p.cells.length,1);near(p.cells[0].fraction,.1);assert.equal(p.mode,'full');}select(a,'116');const d=a.inspect('116').phase;a.click('motion-toggle');a.tick(0);a.tick(1000);near(a.inspect('116').phase,(d+.25)%1);assert.equal(a.inspect('116').mode,'passage');
});

test('wind toggle, reduced motion and missing Canvas retain all selectable raw observations',()=>{
 const a=load(),values=plain(a.state().values);a.click('motion-toggle');a.checked('streaks-toggle',false);assert.equal(a.renderState().flow.renderedStations,0);assert.match(a.nodes['motion-status'].textContent,/바람 기호 숨김/);a.checked('streaks-toggle',true);assert.ok(a.renderState().flow.renderedStations>0);a.setReducedMotion(true);assert.equal(a.state().motion,false);assert.deepEqual(plain(a.state().values),values);const b=load({canvasAvailable:false});assert.equal(b.state().stations,638);assert.equal(b.renderState().flow.canvasAvailable,false);assert.equal(b.nodes['import-status'].hidden,false);assert.match(b.nodes['import-status'].textContent,/Canvas/);select(b,'146');assert.equal(b.nodes['wind-value'].textContent,String(sample(60,1,'146').speed));
});

test('boundary selection, keyboard station navigation and help work without optional removed UI',()=>{
 const a=load(),values=plain(a.state().values);a.click('boundary-district');assert.equal(a.window.AdminMap.state().level,'district');assert.ok(a.nodes['region-select'].children.length>200);a.click('boundary-none');assert.equal(a.nodes['region-select'].disabled,true);a.click('boundary-province');assert.equal(a.nodes['region-select'].disabled,false);const index=history.stations.findIndex(s=>s.id==='108');a.marker('108').emit('keydown',{key:'ArrowRight'});assert.equal(a.state().selected,history.stations[index+1].id);assert.equal(a.marker(a.state().selected).focused,true);a.click('help-button');assert.equal(a.nodes.help.hidden,false);assert.equal(a.nodes['help-button'].getAttribute('aria-expanded'),'true');a.click('help-button');assert.equal(a.nodes.help.hidden,true);assert.deepEqual(plain(a.state().values),values);
});
