/* One deterministic SVG renderer is used by the page and the exported graphic. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('../comparison/core.js'):root.WindComparisonCore,typeof module==='object'&&module.exports?require('./core.js'):root.WindVectorCore);if(typeof module==='object'&&module.exports)module.exports=api;else root.WindVectorRender=api;})(typeof globalThis!=='undefined'?globalThis:this,function(C,V){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const n=v=>Number(v.toFixed(3)),text=(x,y,s,a='')=>`<text x="${n(x)}" y="${n(y)}" ${a}>${esc(s)}</text>`,line=(x1,y1,x2,y2,a='')=>`<line x1="${n(x1)}" y1="${n(y1)}" x2="${n(x2)}" y2="${n(y2)}" ${a}/>`;
const title=s=>`<title>${esc(s)}</title>`,point=s=>({x:s.status==='valid'?Math.sin(s.to*Math.PI/180)*s.record.speedMps:0,y:s.status==='valid'?-Math.cos(s.to*Math.PI/180)*s.record.speedMps:0});
const svg=(w,h,s,label)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}"><g font-family="Arial, Noto Sans CJK KR, sans-serif">${s}</g></svg>`;
function polar(entry){const W=590,H=550,cx=295,cy=262,R=198,k=R/4;let s=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="#f7f9f7"/>`;
 for(let r=1;r<=4;r++){s+=`<circle cx="${cx}" cy="${cy}" r="${r*k}" fill="none" stroke="#dbe4de"/>`+text(cx+5,cy-r*k+14,`${r} m/s`,'font-size="10" fill="#778a81"');}
 for(let a=0;a<8;a++){const t=a*Math.PI/4;s+=line(cx,cy,cx+Math.sin(t)*R,cy-Math.cos(t)*R,'stroke="#e2e9e4"')+text(cx+Math.sin(t)*(R+22),cy-Math.cos(t)*(R+22)+4,['N','NE','E','SE','S','SW','W','NW'][a],'text-anchor="middle" font-size="12" fill="#556f62"');}
 for(let i=1;i<entry.slots.length;i++){const a=entry.slots[i-1],b=entry.slots[i];if(!V.connectable(a,b))continue;const p=point(a),q=point(b);s+=line(cx+p.x*k,cy+p.y*k,cx+q.x*k,cy+q.y*k,`class="mean-segment" stroke="${C.timeColor(b.minute)}" stroke-width=".8" stroke-opacity=".4" data-from-minute="${a.minute}" data-to-minute="${b.minute}"`);}
 const observed=entry.slots.filter(p=>p.n>0);
 for(const p of observed){const q=point(p);s+=`<circle class="mean-hit" data-bin="${p.minute}" cx="${n(cx+q.x*k)}" cy="${n(cy+q.y*k)}" r="4" fill="#000" fill-opacity="0" pointer-events="all">${title(V.describeMean(p))}</circle>`;}
 for(const p of observed.filter(p=>p.minute%60===0)){const q=point(p),major=p.minute%360===0,x=cx+q.x*k,y=cy+q.y*k;let glyph=`<circle cx="${n(x)}" cy="${n(y)}" r="${major?4.9:4.1}" fill="${p.status==='calm'?'white':C.timeColor(p.minute)}" stroke="${p.status==='calm'?C.timeColor(p.minute):'white'}" stroke-width="${major?1.6:1.3}"/>`;if(p.partial)glyph+=`<path d="M${n(x)} ${n(y-7)}l7 7-7 7-7-7Z" fill="none" stroke="#89592c" stroke-width="1.4"/>`;if(p.status==='cancellation')glyph=`<path d="M${n(x-5)} ${n(y-5)}l10 10m0-10-10 10" fill="none" stroke="#a2506a" stroke-width="1.7"/>`;s+=`<g class="mean-hour" data-bin="${p.minute}" data-partial="${p.partial}">${title(V.describeMean(p)+' · 구간 시작 시각')} ${glyph}</g>`;}
 // No visible minute cloud: only averaged path, hourly markers, 3-hour labels.
 const occupied=[];
 for(const p of observed.filter(p=>p.minute%180===0)){const q=point(p),px=cx+q.x*k,py=cy+q.y*k,tx=px+(px>=cx?14:-14);let ty=py-13,tries=0;while(occupied.some(o=>Math.abs(o.x-tx)<50&&Math.abs(o.y-ty)<18)&&tries++<20)ty+=19;ty=Math.max(26,Math.min(H-70,ty));occupied.push({x:tx,y:ty});s+=line(px,py,tx,ty-4,`stroke="${C.timeColor(p.minute)}" stroke-width=".8" pointer-events="none"`)+text(tx,ty,C.clock(p.minute).slice(0,2),`class="mean-label" data-hour="${p.minute/60}" text-anchor="${px>=cx?'start':'end'}" font-size="11" font-weight="600" fill="#324e40" stroke="white" stroke-width="3" paint-order="stroke" pointer-events="none"`);}
 s+=text(cx,H-39,'각도 TO · 반지름 벡터평균 크기 m/s','text-anchor="middle" font-size="12" fill="#456451"')+text(cx,H-20,'정시 표시는 구간 시작 · 평균된 값의 연결','text-anchor="middle" font-size="11" fill="#738479"');
 return svg(W,H,s,`${entry.widthMinutes}분 구간 벡터평균 Polar. 공통 0–4 m/s 척도. 정시 마커는 구간 시작 시각`);
}
function path(entry,mode='mean'){const W=1160,H=504,left=70,right=28,top=34,row=18,bottom=top+row*16,x=m=>left+m/1439*(W-left-right),y=l=>top+(l+.5)*row,stepMode=mode==='step';let s='';
 const bands=['#f4f6fa','#f6f9f8','#fbfaf5','#faf6f8'];for(let i=0;i<4;i++){const start=i*360,end=Math.min(1439,(i+1)*360);s+=`<rect x="${n(x(start))}" y="${top}" width="${n(x(end)-x(start))}" height="${bottom-top}" fill="${bands[i]}"/>`;s+=text(x(start)+9,20,['00–06','06–12','12–18','18–24'][i],'font-size="10" fill="#86918c"');}
 for(let i=0;i<16;i++)s+=line(left,y(i),W-right,y(i),'stroke="#e3e9e5" stroke-width=".7"')+text(left-14,y(i)+4,C.LANES[i],'text-anchor="end" font-size="11" fill="#60746c"');
 for(const m of [0,180,360,540,720,900,1080,1260,1439])s+=line(x(m),top,x(m),bottom,'stroke="#dbe3de" stroke-width=".7"')+text(x(m),bottom+20,C.clock(m),`text-anchor="${m===0?'start':m===1439?'end':'middle'}" font-size="11" fill="#60746c"`);
 const describe=stepMode?V.describeStep:V.describeMean,slots=entry.slots;
 for(let i=1;i<slots.length;i++){const a=slots[i-1],b=slots[i];const ok=stepMode?a.status==='valid'&&b.status==='valid'&&b.minute===a.minute+1:V.connectable(a,b);if(!ok)continue;
  if(stepMode){s+=line(x(a.minute),y(C.lane(a.to)),x(b.minute),y(C.lane(a.to)),'class="step-hold" stroke="#48645d" stroke-width="1.1"');if(C.lane(a.to)!==C.lane(b.to)){for(const seg of V.laneSegments({...a,minute:b.minute},b,true))s+=line(x(seg.x1),y(seg.y1),x(seg.x2),y(seg.y2),`class="step-change" data-wrap="${seg.wrap}" stroke="#48645d" stroke-width="1.1"`);}}
  else for(const seg of V.laneSegments(a,b))s+=line(x(seg.x1),y(seg.y1),x(seg.x2),y(seg.y2),`class="mean-path" data-wrap="${seg.wrap}" stroke="#48645d" stroke-width="1.1"`);
 }
 for(const p of slots.filter(p=>p.status==='valid')){const yy=y(C.lane(p.to)),attr=stepMode?`data-minute="${p.minute}"`:`data-bin="${p.minute}"`;s+=`<circle ${attr} cx="${n(x(p.minute))}" cy="${n(yy)}" r="${stepMode?3:1.9}" fill="#48645d" fill-opacity="${stepMode?0:1}" pointer-events="all">${title(describe(p))}</circle>`;if(p.partial)s+=`<path ${attr} d="M${n(x(p.minute))} ${n(yy-5)}l5 5-5 5-5-5Z" fill="white" stroke="#89592c">${title(describe(p))}</path>`;}
 const st=376,sb=422,sy=v=>sb-v/4*(sb-st);s+=text(left-14,st+4,'4','text-anchor="end" font-size="10" fill="#60746c"')+text(left-14,sb+4,'0','text-anchor="end" font-size="10" fill="#60746c"')+text(12,364,'m/s','font-size="10" fill="#60746c"');for(const v of [0,2,4])s+=line(left,sy(v),W-right,sy(v),'stroke="#e3e9e5" stroke-width=".7"');
 for(let i=1;i<slots.length;i++){const a=slots[i-1],b=slots[i],ok=stepMode?a.status==='valid'&&b.status==='valid':V.connectable(a,b);if(!ok)continue;const xx=x(b.minute);if(stepMode)s+=line(x(a.minute),sy(a.record.speedMps),xx,sy(a.record.speedMps),'stroke="#48645d" stroke-width=".9"')+line(xx,sy(a.record.speedMps),xx,sy(b.record.speedMps),'stroke="#48645d" stroke-width=".9"');else s+=line(x(a.minute),sy(a.record.speedMps),xx,sy(b.record.speedMps),'stroke="#48645d" stroke-width=".9"');}
 for(const p of slots.filter(p=>p.record&&Number.isFinite(p.record.speedMps))){const attr=stepMode?`data-minute="${p.minute}"`:`data-bin="${p.minute}"`;s+=`<circle ${attr} cx="${n(x(p.minute))}" cy="${n(sy(p.record.speedMps))}" r="${stepMode?2.5:1.5}" fill="#48645d" fill-opacity="${stepMode?0:1}">${title(describe(p))}</circle>`;}
 const rows=[['calm','무풍 ○',448,'#71877e'],['missing','결측 ×',463,'#a86544'],['unavailable','미확보 ·',478,'#9ca8a2'],['cancellation','상쇄 ×',493,'#a2506a']];for(const [status,label,yy,color]of rows){s+=text(left-10,yy+3,label,'text-anchor="end" font-size="9" fill="#60746c"')+line(left,yy,W-right,yy,'stroke="#eef1ee"');for(const p of slots.filter(p=>p.status===status)){const width=stepMode?1:Math.max(2,x(Math.min(1439,p.end))-x(p.minute));s+=`<rect ${stepMode?`data-minute="${p.minute}"`:`data-bin="${p.minute}"`} x="${n(x(p.minute))}" y="${yy-3}" width="${n(width)}" height="6" fill="${color}">${title(describe(p))}</rect>`;}}
 return svg(W,H,s,`${stepMode?'5분 지속 상태변화':'5분 구간 벡터평균'} Wind Path. 실제 24시간, 16 TO 방향행, 단색, 분리된 풍속 띠`);
}
return {esc,polar,path};
});
