(function(){
'use strict';
const M=window.WindMatrixCore,C=window.WindComparisonCore,R=window.WindComparisonRender,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const model=M.prepareDataset(window.WIND_MATRIX_DATA);let active=model.stations.find(s=>s.station.id==='146'),minute=1,view=$('map-view')?'map':'station',buttons=[];
const stationListeners=[],minuteListeners=[];
const arrow=b=>`<svg viewBox="0 0 20 20" aria-hidden="true"><g transform="rotate(${b} 10 10)"><path d="M10 16V4M6.5 7.5 10 4l3.5 3.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g></svg>`;
const fmt=n=>n.toLocaleString('en-US');
function node(tag,attrs={}){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;}
function setNavigation(){
  $('map-tab').classList.toggle('active',view==='map');$('map-tab').setAttribute('aria-current',view==='map'?'page':'false');
  $('station-tab').classList.toggle('active',view==='station');$('station-tab').setAttribute('aria-current',view==='station'?'page':'false');
  $('map-tab').setAttribute('href',`index.html#station=${active.station.id}`);
  $('station-tab').setAttribute('href',`VECTOR_COMPARE.html#station=${active.station.id}`);
  if($('back-map'))$('back-map').setAttribute('href',`index.html#station=${active.station.id}`);
}
function showView(next){if(next!==view)window.location.href=`${next==='map'?'index':'VECTOR_COMPARE'}.html#station=${active.station.id}`;}
function chooseStation(id,writeHistory=true){const s=model.stations.find(s=>s.station.id===id);if(!s)return;active=s;minute=Math.min(1439,Math.max(0,minute));setNavigation();
  if(view==='map'){if(writeHistory)showView('station');else renderMap();}
  else{renderStation();if(writeHistory)window.location.hash=`station=${active.station.id}`;}
}
function renderMap(){const t=window.WIND_MATRIX_TERRAIN||{},bounds=t.bounds||[125.8,35.3,128,36.4],project=([lon,lat])=>[(lon-bounds[0])/(bounds[2]-bounds[0])*540,(bounds[3]-lat)/(bounds[3]-bounds[1])*300];
if(t.available)$('terrain-image').setAttribute('href',t.asset);else $('terrain-error').hidden=false;
// Equirectangular terrain: horizontal distance at the map's central latitude.
const middleLatitude=(bounds[1]+bounds[3])/2,kmPerLongitudeDegree=6371.0088*Math.PI/180*Math.cos(middleLatitude*Math.PI/180),scaleWidth=20/kmPerLongitudeDegree*540/(bounds[2]-bounds[0]);
$('map-scale-line').setAttribute('d',`M0 -3V3M0 0H${scaleWidth}M${scaleWidth/2} -3V3M${scaleWidth} -3V3`);
const b=$('map-boundaries');b.replaceChildren();for(const f of t.boundaries||[]){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;const d=polys.map(p=>p.map(r=>r.map((pt,i)=>`${i?'L':'M'}${project(pt).map(n=>n.toFixed(2)).join(' ')}`).join('')+'Z').join('')).join('');b.appendChild(node('path',{d,fill:'none',stroke:'#718570','stroke-width':'.7','stroke-opacity':'.65'}));}
const g=$('map-stations');g.replaceChildren();for(const s of model.stations){const pos=M.historicalPosition(s.station,M.timestampAt(0));if(!pos)continue;const [x,y]=project([pos.lon,pos.lat]);const mark=node('g',{class:`map-station${s.counts.valid?'':' unacquired'}${s===active?' selected':''}`,transform:`translate(${x} ${y})`,tabindex:'0',role:'button','aria-label':`${s.station.name} ${s.station.network} ${s.station.id}, 수치 유효 ${s.counts.valid}, 결측 ${s.counts.missing}, 미확보 ${s.counts.unavailable}. Station View 열기`});const title=node('title');title.textContent=`${s.station.name} · ${s.station.id} · ${s.counts.valid?fmt(s.counts.valid)+'분 수치 유효':'풍향·풍속 미확보'}`;mark.appendChild(title);mark.appendChild(node('circle',{r:s===active?6:s.counts.valid?4.5:3}));if(s.counts.valid){const label=node('text',{x:8,y:3});label.textContent=s.station.name;mark.appendChild(label);}const choose=()=>chooseStation(s.station.id);mark.addEventListener('click',choose);mark.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});g.appendChild(mark);}}
function renderLists(){for(const s of model.stations){const option=document.createElement('option');option.value=s.station.id;option.textContent=`${s.station.name} · ${s.station.network} ${s.station.id}${s.counts.valid?'':' · 미확보'}`;if($('station-select'))$('station-select').appendChild(option);if(!$('map-station-list'))continue;const button=document.createElement('button');button.type='button';const name=document.createElement('strong');name.textContent=`${s.station.name} ${s.station.id}`;const counts=document.createElement('span');counts.textContent=s.counts.valid?`유효 ${fmt(s.counts.valid)} · 결측 ${s.counts.missing}`:'위치만 확인 · 1,440분 미확보';button.append(name,counts);button.addEventListener('click',()=>chooseStation(s.station.id));$(s.station.network==='AWS'?'aws-list':'map-station-list').appendChild(button);}}
function renderStation(){const pos=M.historicalPosition(active.station,M.timestampAt(0));$('station-name').textContent=active.station.name;$('station-id').textContent=`${active.station.network} ${active.station.id}`;$('station-location').textContent=`2024.10.06 · 00:00–23:59 KST${pos?` · ${pos.lat.toFixed(4)}° N, ${pos.lon.toFixed(4)}° E · 당일 확인 위치`:''}`;$('station-select').value=active.station.id;
for(const [id,key]of [['usable-count','valid'],['calm-count','calm'],['missing-count','missing'],['unacquired-count','unavailable']])$(id).textContent=fmt(active.counts[key]);$('completeness-note').textContent=active.counts.valid?`00:00 미확보 · ${active.counts.missing?'확보분 결측은 원본 빈칸':'00:01–23:59 수치 유효'} · QC 미확인`:'관측 자료 미확보 · 당일 위치 이력만 확인';$('empty-notice').hidden=active.counts.unavailable!==1440;
$('path-chart').innerHTML=R.path(active);$('polar-chart').innerHTML=R.polar(active);renderMatrix();for(const notify of stationListeners)notify(active);selectMinute(minute);}
function renderMatrix(){const table=$('wind-matrix');table.tHead.replaceChildren();table.tBodies[0].replaceChildren();buttons=[];const row=document.createElement('tr');for(let col=-1;col<60;col++){const th=document.createElement('th');th.scope='col';th.textContent=col<0?'시/분':String(col).padStart(2,'0');row.appendChild(th);}table.tHead.appendChild(row);
for(let h=0;h<24;h++){const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=String(h).padStart(2,'0');tr.appendChild(th);for(let m=0;m<60;m++){const i=h*60+m,s=active.slots[i],td=document.createElement('td'),b=document.createElement('button');b.type='button';b.className='minute-cell '+s.status;b.dataset.minute=String(i);b.tabIndex=i===minute?0:-1;b.setAttribute('aria-label',C.describe(s));b.title=C.describe(s);if(s.status==='valid'){b.innerHTML=arrow(s.to);b.style.backgroundColor=M.speedColor(s.record.speedMps);}else b.textContent=s.status==='calm'?'○':s.status==='missing'?'×':'·';b.addEventListener('click',()=>selectMinute(i));b.addEventListener('mouseenter',()=>showDetail(i));b.addEventListener('mouseleave',()=>showDetail(minute));b.addEventListener('focus',()=>showDetail(i));b.addEventListener('keydown',e=>{let next=i;switch(e.key){case'ArrowRight':next=i+1;break;case'ArrowLeft':next=i-1;break;case'ArrowUp':next=i-60;break;case'ArrowDown':next=i+60;break;case'Home':next=e.ctrlKey?0:h*60;break;case'End':next=e.ctrlKey?1439:h*60+59;break;default:return;}e.preventDefault();selectMinute(Math.max(0,Math.min(1439,next)));buttons[minute].focus();});td.appendChild(b);tr.appendChild(td);buttons.push(b);}table.tBodies[0].appendChild(tr);}}
function selectMinute(next){if(!Number.isInteger(next)||next<0||next>1439)return false;if(buttons[minute]){buttons[minute].classList.remove('selected');buttons[minute].tabIndex=-1;buttons[minute].setAttribute('aria-pressed','false');}minute=next;if(buttons[minute]){buttons[minute].classList.add('selected');buttons[minute].tabIndex=0;buttons[minute].setAttribute('aria-pressed','true');}$('minute-input').value=C.clock(minute);showDetail(minute);return true;}
function showDetail(i){const s=active.slots[i],r=s.record; $('detail-status').textContent=C.statusText[s.status];$('detail-time').textContent=C.clock(i)+' KST';$('detail-speed').textContent=r?.speedMps===null||r?.speedMps===undefined?'—':r.speedMps;$('detail-from').textContent=C.rawFrom(s);$('detail-to').textContent=s.to===null?'정의하지 않음':String(Number(s.to.toFixed(10)))+'°';$('detail-arrow').innerHTML=s.status==='valid'?arrow(s.to):`<span>${s.status==='calm'?'○':s.status==='missing'?'×':'·'}</span>`;$('detail-note').textContent=s.status==='calm'?'원본 풍속 0 m/s · 원본 FROM은 보존하되 TO 방향을 정의하지 않습니다':s.status==='unavailable'?'원본 행 미확보 · 관측 결측으로 간주하지 않습니다':s.status==='missing'?'원본 값 결측 · 빈칸을 메우지 않으며 연결선을 끊습니다':'실제 1분 평균 관측 · A의 방향행만 16방위로 분류합니다';$('raw-time').textContent=r?.rawValues?.['일시']||r?.timestamp||'원본 행 없음';$('raw-values').textContent=r?JSON.stringify(r.rawValues||{}):'원본 행 없음';$('raw-row').textContent=r?.sourceRow===undefined?'—':r.sourceRow;renderSelection(i);for(const notify of minuteListeners)notify(i);}
function renderSelection(i){const a=$('path-selection'),b=$('polar-selection'),s=active.slots[i];if(a){const x=70+i/1439*1062;a.innerHTML=`<line x1="${x}" x2="${x}" y1="28" y2="414" stroke="#b87f3c" stroke-width="1" stroke-dasharray="3 3"/>${s.status==='valid'?`<circle cx="${x}" cy="${34+(C.lane(s.to)+.5)*18}" r="4" fill="none" stroke="#9c672d" stroke-width="1.5"/>`:''}`;}if(b){const p=C.polarPoint(s);b.innerHTML=p?`<circle cx="${295+p.x*49.5}" cy="${262+p.y*49.5}" r="7" fill="none" stroke="#253d32" stroke-width="1.5"/>`:'';}}
function chartKey(e){if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1439:minute+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1);selectMinute(Math.min(1439,Math.max(0,next)));}}
if(view==='station'){
for(const id of ['path-chart','polar-chart']){const chart=$(id);chart.addEventListener('keydown',chartKey);chart.addEventListener('mouseleave',()=>showDetail(minute));chart.addEventListener('click',e=>{const p=e.target.closest('[data-minute]');if(p)selectMinute(Number(p.getAttribute('data-minute')));else if(id==='path-chart'){const svg=chart.querySelector('svg'),box=svg.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*1160;if(x>=70&&x<=1132)selectMinute(Math.round((x-70)/1062*1439));}});chart.addEventListener('mousemove',e=>{const p=e.target.closest('[data-minute]');if(p)showDetail(Number(p.getAttribute('data-minute')));else if(id==='path-chart'){const svg=chart.querySelector('svg'),box=svg.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*1160;if(x>=70&&x<=1132)showDetail(Math.round((x-70)/1062*1439));}});}
$('minute-input').addEventListener('change',e=>{const m=/^(\d{2}):(\d{2})$/.exec(e.target.value);if(!m||+m[1]>23||+m[2]>59){e.target.value=C.clock(minute);return;}selectMinute(+m[1]*60+(+m[2]));});$('previous-minute').addEventListener('click',()=>selectMinute(Math.max(0,minute-1)));$('next-minute').addEventListener('click',()=>selectMinute(Math.min(1439,minute+1)));$('station-select').addEventListener('change',e=>chooseStation(e.target.value));
}else{
$('open-jeonju').addEventListener('click',()=>chooseStation('146'));$('terrain-image').addEventListener('error',()=>$('terrain-error').hidden=false);
}
function fromHash(){const match=/^#station=(\d+)$/.exec(window.location.hash);const id=match&&model.stations.some(s=>s.station.id===match[1])?match[1]:'146';chooseStation(id,false);}
window.addEventListener('hashchange',fromHash);
if(view==='station'){
for(const stop of M.SPEED_STOPS){const el=document.createElement('span');el.innerHTML=`<i style="background:${stop.color}"></i>${stop.label}`;$('matrix-speed-key').appendChild(el);}const unit=document.createElement('span');unit.textContent='m/s';$('matrix-speed-key').appendChild(unit);
}
renderLists();fromHash();
window.WindStationComparison={selectStation:chooseStation,selectMinute,inspectMinute:showDetail,showView,getActiveStation:()=>active,
  onStationChange(fn){stationListeners.push(fn);fn(active);},onMinuteChange(fn){minuteListeners.push(fn);fn(minute);},
  getState:()=>({view,stationId:active.station.id,minute,counts:{...active.counts},geometry:C.build(active)})};
})();
